# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d374179412884374f1a7d2d38582ad53e3ef31a7df6fb7c527302dc7869a94b4920e652efb25e01d7b1ba91d1e224af08add25004dcba6f8ebe9c63cbbbe2aa2

test:
  secret_key_base: 78aec23704a99c86817ef79498caeb55b6d6fc9c8d168dcaf99bbfb3989b4f1676c3a9ba21722550a960a79f20b2db1e47b1bfa731e6049bd70684dbe8292ad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
